import _cython_3_1_6
import enum
from typing import Callable, ClassVar

__test__: dict
generate_dataset: _cython_3_1_6.cython_function_or_method

class DatasetDistribution(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    CLUSTERED: ClassVar[DatasetDistribution] = ...
    RANDOM: ClassVar[DatasetDistribution] = ...
    RANDOM_CLUSTERED: ClassVar[DatasetDistribution] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""
