def validate_matrix(mat, mat_name, num_locations) -> None: ...
def validate_positive_df(df, df_name) -> None: ...
def validate_positive(var, var_name) -> None: ...
def validate_non_negative(var, var_name) -> None: ...
def validate_size(var_1, var_1_str, var_2, var_2_str) -> None: ...
def validate_time_windows(earliest, latest, size, size_str) -> None: ...
def validate_range(var, var_name, min, max) -> None: ...
