from cuopt.linear_programming.solver.solver_parameters import CUOPT_ABSOLUTE_PRIMAL_TOLERANCE as CUOPT_ABSOLUTE_PRIMAL_TOLERANCE, CUOPT_MIP_INTEGRALITY_TOLERANCE as CUOPT_MIP_INTEGRALITY_TOLERANCE, CUOPT_RELATIVE_PRIMAL_TOLERANCE as CUOPT_RELATIVE_PRIMAL_TOLERANCE

def validate_variable_bounds(data, settings, solution) -> None: ...
def validate_constraint_sanity_per_row(data, solution, cost, abs_tolerance, rel_tolerance): ...
def validate_objective_sanity(data, solution, cost, tolerance) -> None: ...
def check_solution(data, setting, solution, cost) -> None: ...
